### ISSUE TITLE
Make `NftReward` contract upgradeable

### ISSUE THREAD

**Issue by rndquu** [ubiquity/nft-rewards#1]
There is the [NftReward](https://github.com/ubiquity/nft-rewards/blob/f3aff74902c9c9814bdb0ffb1c213fbe7cba9360/src/NftReward.sol) contract responsible for minting NFTs using a minter's signature. We should make the contract to be upgradeable.

What should be done:
1. Make [NftReward](https://github.com/ubiquity/nft-rewards/blob/f3aff74902c9c9814bdb0ffb1c213fbe7cba9360/src/NftReward.sol) contract upgradeable (using openzeppelin's [UUPS contracts](https://docs.openzeppelin.com/contracts/5.x/api/proxy#UUPSUpgradeable))
2. Update the [deployment script](https://github.com/ubiquity/nft-rewards/blob/f3aff74902c9c9814bdb0ffb1c213fbe7cba9360/script/Deploy001_NftReward.s.sol)

**Comment by rndquu** [comment]
> /start

You're free to start, not sure why the bot is not responding

**Comment by 0x4007** [comment]
I think it assigns now only on pull request opened. I don't think this was intentional but I'm also okay with this behavior.

**Comment by 0x4007** [comment]
@gpylypchuk can you set your wallet address so that the bot can assign you, and you can receive rewards?
