### ISSUE TITLE
Deploy with `CREATE2`

### ISSUE THREAD

**Issue by rndquu** [ubiquity/nft-rewards#2]
There is the [deployment script](https://github.com/ubiquity/nft-rewards/blob/f3aff74902c9c9814bdb0ffb1c213fbe7cba9360/script/Deploy001_NftReward.s.sol) responsible for creating a new [NftReward](https://github.com/ubiquity/nft-rewards/blob/f3aff74902c9c9814bdb0ffb1c213fbe7cba9360/src/NftReward.sol) contract.

The [NftReward's](https://github.com/ubiquity/nft-rewards/blob/f3aff74902c9c9814bdb0ffb1c213fbe7cba9360/src/NftReward.sol) contract address should be the same across all networks.

What should be done:
- update the [deployment script](https://github.com/ubiquity/nft-rewards/blob/f3aff74902c9c9814bdb0ffb1c213fbe7cba9360/script/Deploy001_NftReward.s.sol) to use `create2` so that we could have the same [NftReward's](https://github.com/ubiquity/nft-rewards/blob/f3aff74902c9c9814bdb0ffb1c213fbe7cba9360/src/NftReward.sol) contract address across all networks

P.S. Note to self. When current issues is solved:
1. Redeploy the NFT reward contract
2. Update [readme](https://github.com/ubiquity/nft-rewards) with the new address
3. Set minter (defined [here](https://github.com/ubiquibot/comment-incentives/blob/d68ab4b4635e19d7facbd06259d25f4f30ea0e90/src/handlers/issue/generate-erc721-permit-signature.ts#L6)) in the contract's storage via `setMinter()`
4. Update NFT contract address [here](https://github.com/ubiquibot/comment-incentives/blob/d68ab4b4635e19d7facbd06259d25f4f30ea0e90/src/handlers/issue/generate-erc721-permit-signature.ts#L7)

**Comment by guha-rahul** [comment]
Hey i am interested in solving this issue. What hard coded variables do we need to manage?

**Comment by 0x4007** [comment]
I might have messed up the specification @rndquu perhaps you can clarify and re edit the spec

**Comment by rndquu** [comment]
> Hey i am interested in solving this issue. What hard coded variables do we need to manage?

No need to change hard coded values, I'll handle it once the current issue is solved. As a part of this issue we should just refactor the deployment script to use `create2`.

**Comment by guha-rahul** [comment]
When i am trying to start the bounty, the bot says that it cannot be self assigned in this issue https://github.com/ubiquity/devpool-directory/issues/1026.

**Comment by rndquu** [comment]
> When i am trying to start the bounty, the bot says that it cannot be self assigned in this issue [ubiquity/devpool-directory#1026](https://github.com/ubiquity/devpool-directory/issues/1026).

Try in the current issue

**Comment by guha-rahul** [comment]
@rndquu , still the bot doesnt assign me the role.

**Comment by rndquu** [comment]
> @rndquu , still the bot doesnt assign me the role.

Smth is wrong with the bot then, you may start the issue anyway and `/start` the issue later when the bot is back live

**Comment by 0x4007** [comment]
Looks like you didn't register your wallet. Bot is supposed to throw an error and tell you to register before allowing an assign @guha-rahul 

Please set it and we can send the wxdai on gnosis chain

**Comment by guha-rahul** [comment]
Hey so should i proceed directly with "/wallet" or "/start"? 
I am also curious so i will be paid (1.7+47.6) wxdai right instead of 100 wxdai and on what basis the calculation has been ? Sorry if this is a very trivial question.

**Comment by 0x4007** [comment]
Yes try the wallet command. 100 WXDAI. It's supposed to be based on how much everybody contributed to solving this problem.

**Comment by 0x4007** [comment]
https://gnosisscan.io/tx/0xc20515b2685a62cfaee000c5b65502bce9a29d2d5657cc8a22355761cc4c522c
