### ISSUE TITLE
Invalidate nonce

### ISSUE THREAD

**Issue by rndquu** [ubiquity/nft-rewards#4]
Owner should be able to invalidate [nonce](https://github.com/ubiquity/nft-rewards/blob/31871eb28c84fe0b95b413e2ea420c8c52191255/src/NftReward.sol#L23) for already signed mint request.

What should be done:
1. Add a new method `invalidateNonce()` where owner can pass a nonce value and invalidate mint request.
2. Cover with tests the `invalidateNonce()` method

**Comment by gpylypchuk** [comment]
Do you mean a method like this?

```solidity
function invalidateNonce(uint256 _nonceValue) external onlyOwner {
        nonceRedeemed[_nonceValue] = true;
}
```

So when your're going to mint, that nonce is already used and the require should fail.

**Comment by rndquu** [comment]
> Do you mean a method like this?
> 
> ```solidity
> function invalidateNonce(uint256 _nonceValue) external onlyOwner {
>         nonceRedeemed[_nonceValue] = true;
> }
> ```
> 
> So when your're going to mint, that nonce is already used and the require should fail.

Exactly

**Comment by molecula451** [comment]
> ```diff
> ! action has an uncaught error
> ```

**Comment by molecula451** [comment]
thanks for the PR @gpylypchuk hold while we get you the bot generate the permit claim to you

**Comment by gpylypchuk** [comment]
> thanks for the PR @gpylypchuk hold while we get you the bot generate the permit claim to you

yes! no problem :)

**Comment by 0x4007** [comment]
Weird that it didn't even start the process here. Maybe I broke it by changing the GitHub secret in the other organization. Although I would've expected a crash after the calculating rewards comment is posted.

**Comment by molecula451** [comment]
yeah it looks like on the last action it throw the key/pair incorrect that we know

**Comment by molecula451** [comment]
pavlovcik let's not forget to issue this contributors permit

**Comment by 0x4007** [comment]
We can try regenerating here.
